@echo off
echo Adding new files (README etc)...
git add .
echo Committing changes...
git commit -m "Add README and final project structure"
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
