@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Final version: Audio Streaming App"
echo Renaming branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/Honoured-1-byte/Audio_Streaming_app.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
